aggregator-main:
    path:       /
    defaults:   { _controller: 'SimpleSAML\Module\aggregator2\Controller\Aggregator::main' }
aggregator-get:
    path:       /get
    defaults:   { _controller: 'SimpleSAML\Module\aggregator2\Controller\Aggregator::get' }
